name: CI/CD pack spring boot 

on:
  push:
    branches:
      - 'main'

env: 
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_PACK_NAME }}

jobs:
  containers:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pack CLI
        run: |
          wget https://github.com/buildpacks/pack/releases/download/v0.29.0/pack-v0.29.0-linux.tgz -O /tmp/pack.tgz
          sudo tar -xf /tmp/pack.tgz -C /usr/local/bin/ pack
          pack version

      - name: Build image with pack
        run: |
          pack build $IMAGE_NAME \
            --builder paketobuildpacks/builder:base \
            --path . \
            --env "BP_JAVA_VERSION=17.*"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Retag image LATEST with image id from the last build
        run: docker tag ${{ steps.vars.outputs.image_id }} ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_PACK_NAME }}:latest

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_PACK_NAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_PACK_NAME }}:latest
